-- AlterTable
ALTER TABLE "Carton" ADD COLUMN     "bigCartonPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bigCartonsQuantity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "smallCartonPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "smallCartonsQuantity" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "quantity" SET DEFAULT 0,
ALTER COLUMN "price" SET DEFAULT 0;
